package com.jason.calculator;
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptException;
import javax.swing.JOptionPane;
/**
 *
 * @author warja
 */
public class Calculator extends javax.swing.JFrame {
    int[] num = new int[1];
    String[] equ = new String[10];
    String equasion = "",Display = "",type = "D",Output ="N";
    //Exceptions That Could Be Avoided
    int ETCBA = 0, abs = 0, place = 10;
    boolean shift=false;
    ScriptEngineManager mgr = new ScriptEngineManager();
    ScriptEngine engine = mgr.getEngineByName("JavaScript");
    
    
    public String getUnitType()
    { 
        return type;
    }
    public int getPlace()
    { 
        return place;
    }
    public String getOutputType()
    { 
        return Output;
    }
    
    private String Sub(String Convert){
        Convert = Convert.replaceAll("0", "₀");
        Convert = Convert.replaceAll("1", "₁");
        Convert = Convert.replaceAll("2", "₂");
        Convert = Convert.replaceAll("3", "₃");
        Convert = Convert.replaceAll("4", "₄");
        Convert = Convert.replaceAll("5", "₅");
        Convert = Convert.replaceAll("6", "₆");
        Convert = Convert.replaceAll("7", "₇");
        Convert = Convert.replaceAll("8", "₈");
        Convert = Convert.replaceAll("9", "₉"); 
        return Convert;
    }
    
    private String Super(String Convert){
        Convert = Convert.replaceAll("0", "⁰");
        Convert = Convert.replaceAll("1", "¹");
        Convert = Convert.replaceAll("2", "²");
        Convert = Convert.replaceAll("3", "³");
        Convert = Convert.replaceAll("4", "⁴");
        Convert = Convert.replaceAll("5", "⁵");
        Convert = Convert.replaceAll("6", "⁶");
        Convert = Convert.replaceAll("7", "⁷");
        Convert = Convert.replaceAll("8", "⁸");
        Convert = Convert.replaceAll("9", "⁹");
        Convert = Convert.replaceAll("-", "⁻");
        return Convert;
    }
       

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtAreaOutput = new javax.swing.JTextField();
        TxtAreaDebug = new javax.swing.JTextField();
        Btn0 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        BtnDot = new javax.swing.JButton();
        BtnEquals = new javax.swing.JButton();
        BtnPlus = new javax.swing.JButton();
        BtnMinus = new javax.swing.JButton();
        BtnMultiply = new javax.swing.JButton();
        BtnDevide = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnSqr = new javax.swing.JButton();
        BtnOpen = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();
        BtnRoot = new javax.swing.JButton();
        BtnCubeRoot = new javax.swing.JButton();
        BtnCustRoot = new javax.swing.JButton();
        BtnFraction = new javax.swing.JButton();
        BtnMixedFraction = new javax.swing.JButton();
        BtnCos = new javax.swing.JButton();
        BtnSin = new javax.swing.JButton();
        BtnTan = new javax.swing.JButton();
        BtnAbsolute = new javax.swing.JButton();
        Btn11 = new javax.swing.JButton();
        BtnCustRoot2 = new javax.swing.JButton();
        BtnSin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnDot1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnAbsolute1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtAreaOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAreaOutputActionPerformed(evt);
            }
        });

        Btn0.setText("0");
        Btn0.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn0.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn0.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        Btn1.setText("1");
        Btn1.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn1.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn1.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setText("2");
        Btn2.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn2.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn2.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setText("3");
        Btn3.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn3.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn3.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn4.setText("4");
        Btn4.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn4.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn4.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setText("5");
        Btn5.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn5.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn5.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn6.setText("6");
        Btn6.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn6.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn6.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        Btn7.setText("7");
        Btn7.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn7.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn7.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn8.setText("8");
        Btn8.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn8.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn8.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn9.setText("9");
        Btn9.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn9.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn9.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        BtnDot.setText(".");
        BtnDot.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnDot.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnDot.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDotActionPerformed(evt);
            }
        });

        BtnEquals.setText("=");
        BtnEquals.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnEquals.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnEquals.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEqualsActionPerformed(evt);
            }
        });

        BtnPlus.setText("+");
        BtnPlus.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnPlus.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnPlus.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlusActionPerformed(evt);
            }
        });

        BtnMinus.setText("-");
        BtnMinus.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnMinus.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnMinus.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusActionPerformed(evt);
            }
        });

        BtnMultiply.setText("x");
        BtnMultiply.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnMultiply.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnMultiply.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplyActionPerformed(evt);
            }
        });

        BtnDevide.setText("÷");
        BtnDevide.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnDevide.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnDevide.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDevideActionPerformed(evt);
            }
        });

        BtnClear.setText("AC");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        BtnSqr.setText("x²");
        BtnSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSqrActionPerformed(evt);
            }
        });

        BtnOpen.setText("(");
        BtnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpenActionPerformed(evt);
            }
        });

        BtnClose.setText(")");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });

        BtnRoot.setText("√");
        BtnRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRootActionPerformed(evt);
            }
        });

        BtnCubeRoot.setText("³√");
        BtnCubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCubeRootActionPerformed(evt);
            }
        });

        BtnCustRoot.setText("ⁿ√");
        BtnCustRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustRootActionPerformed(evt);
            }
        });

        BtnFraction.setText("⅍");
        BtnFraction.setToolTipText("");
        BtnFraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFractionActionPerformed(evt);
            }
        });

        BtnMixedFraction.setText("n⅍");
        BtnMixedFraction.setToolTipText("");
        BtnMixedFraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMixedFractionActionPerformed(evt);
            }
        });

        BtnCos.setText("cos");
        BtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCosActionPerformed(evt);
            }
        });

        BtnSin.setText("sin");
        BtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSinActionPerformed(evt);
            }
        });

        BtnTan.setText("tan");
        BtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTanActionPerformed(evt);
            }
        });

        BtnAbsolute.setText("ABS");
        BtnAbsolute.setToolTipText("");
        BtnAbsolute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbsoluteActionPerformed(evt);
            }
        });

        Btn11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        Btn11.setText("⚙");
        Btn11.setMaximumSize(new java.awt.Dimension(40, 25));
        Btn11.setMinimumSize(new java.awt.Dimension(40, 25));
        Btn11.setPreferredSize(new java.awt.Dimension(40, 25));
        Btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn11ActionPerformed(evt);
            }
        });

        BtnCustRoot2.setText("asin");
        BtnCustRoot2.setToolTipText("");
        BtnCustRoot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustRoot2ActionPerformed(evt);
            }
        });

        BtnSin1.setText("Shift");
        BtnSin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSin1ActionPerformed(evt);
            }
        });

        jLabel1.setText("xⁿ");

        BtnDot1.setText("x10ⁿ");
        BtnDot1.setMaximumSize(new java.awt.Dimension(40, 25));
        BtnDot1.setMinimumSize(new java.awt.Dimension(40, 25));
        BtnDot1.setPreferredSize(new java.awt.Dimension(40, 25));
        BtnDot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDot1ActionPerformed(evt);
            }
        });

        jLabel2.setText("𝜋");

        BtnAbsolute1.setText("ANS");
        BtnAbsolute1.setToolTipText("");
        BtnAbsolute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbsolute1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Maths");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenu4.setText("jMenu3");
        jMenu1.add(jMenu4);

        jMenu5.setText("jMenu3");
        jMenu1.add(jMenu5);

        jMenu6.setText("jMenu3");
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Physics");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtAreaDebug)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDot1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnCubeRoot)
                                    .addComponent(BtnCustRoot)
                                    .addComponent(BtnRoot)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel1))
                                    .addComponent(BtnSqr))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnOpen)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(BtnClose)
                                                .addGap(61, 61, 61)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BtnFraction)
                                                    .addComponent(BtnMixedFraction))
                                                .addGap(4, 4, 4))
                                            .addComponent(BtnClear, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(BtnCos))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BtnCustRoot2)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(BtnSin)
                                                        .addComponent(BtnTan)))))
                                        .addGap(61, 61, 61))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(BtnAbsolute)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(BtnAbsolute1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(TxtAreaOutput)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnSin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtAreaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtAreaDebug, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSin1))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCos)
                                .addGap(39, 39, 39)
                                .addComponent(BtnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnFraction)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnMixedFraction)
                                        .addGap(69, 69, 69))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnSin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnTan)
                                        .addGap(18, 18, 18)))
                                .addComponent(BtnCustRoot2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnDot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(4, 4, 4)
                                    .addComponent(BtnSqr))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(BtnRoot)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnCubeRoot)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnCustRoot)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnOpen)
                                    .addComponent(BtnClose))
                                .addGap(100, 100, 100)
                                .addComponent(BtnAbsolute)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(BtnAbsolute1)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtAreaOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAreaOutputActionPerformed
      TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_TxtAreaOutputActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        Display = TxtAreaOutput.getText() + Btn0.getText();
        equasion = equasion + Btn0.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn0ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        Display = TxtAreaOutput.getText() + Btn1.getText();
        equasion = equasion + Btn1.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        Display = TxtAreaOutput.getText() + Btn2.getText();
        equasion = equasion + Btn2.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        Display = TxtAreaOutput.getText() + Btn4.getText();
        equasion = equasion + Btn4.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        Display = TxtAreaOutput.getText() + Btn8.getText();
        equasion = equasion + Btn8.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        Display = TxtAreaOutput.getText() + Btn9.getText();
        equasion = equasion + Btn9.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        Display = TxtAreaOutput.getText() + Btn6.getText();
        equasion = equasion + Btn6.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        Display = TxtAreaOutput.getText() + Btn3.getText();
        equasion = equasion + Btn3.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        Display = TxtAreaOutput.getText() + Btn7.getText();
        equasion = equasion + Btn7.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        Display = TxtAreaOutput.getText() + Btn5.getText();
        equasion = equasion + Btn5.getText();
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_Btn5ActionPerformed

    private void BtnDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDevideActionPerformed
        Display = TxtAreaOutput.getText() + BtnDevide.getText();
        equasion = equasion + "/";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnDevideActionPerformed

    private void BtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplyActionPerformed
        Display = TxtAreaOutput.getText() + BtnMultiply.getText();
        equasion = equasion + "*";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnMultiplyActionPerformed

    private void BtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlusActionPerformed
        Display = TxtAreaOutput.getText() + BtnPlus.getText();
        equasion = equasion + "+";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnPlusActionPerformed

    private void BtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusActionPerformed
        Display = TxtAreaOutput.getText() + BtnMinus.getText();
        equasion = equasion + "-";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnMinusActionPerformed

    private void BtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDotActionPerformed
//I would limit the maximum decimal points to 1 per number but the calculator
//I am using for reference has no limit on decimal points.
    equasion = TxtAreaDebug.getText() + BtnDot.getText();
    Display = TxtAreaOutput.getText() + BtnDot.getText();
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    
    }//GEN-LAST:event_BtnDotActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
    equasion = "";
    Display = "";
    TxtAreaOutput.setText(Display);
    TxtAreaDebug.setText(equasion);
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEqualsActionPerformed
        try {
            TxtAreaOutput.setText(String.valueOf(engine.eval(equasion)));
        } catch (ScriptException ex) {
            TxtAreaOutput.setText("Syntax Error");
        }
    }//GEN-LAST:event_BtnEqualsActionPerformed

    private void BtnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpenActionPerformed
    Display = TxtAreaOutput.getText() + BtnOpen.getText();
    equasion = equasion + BtnOpen.getText();
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnOpenActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
    Display = TxtAreaOutput.getText() + BtnClose.getText();
    equasion = equasion + BtnClose.getText();
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCosActionPerformed
    Display = TxtAreaOutput.getText() + "cos(";
    equasion = equasion + " Math.cos(Math.PI / 180 * ";
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnCosActionPerformed

    private void BtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSinActionPerformed
    Display = TxtAreaOutput.getText() + "sin(";
    equasion = equasion + " Math.sin(Math.PI / 180 * ";
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnSinActionPerformed

    private void BtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTanActionPerformed
    Display = TxtAreaOutput.getText() + "tan(";
    equasion = equasion + " Math.tan(Math.PI / 180 * ";
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnTanActionPerformed

    private void BtnSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSqrActionPerformed
        if(!shift)
        {
        String d = JOptionPane.showInputDialog(rootPane,"Please enter the number to be squared");
        Double sqr = Double.parseDouble(d);
        Display = TxtAreaOutput.getText() + d + "²";
        equasion = equasion + "Math.pow("+sqr+",2)";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
        }
        else
        {
        String number = JOptionPane.showInputDialog(rootPane,"Please enter the number");
        String pow = JOptionPane.showInputDialog(rootPane,"Please enter the power");
        equasion = equasion + "Math.pow("+number+","+pow+")";
        pow = Super(pow);
        Display = TxtAreaOutput.getText() + number + pow;
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
        shift = false;
        }
    }//GEN-LAST:event_BtnSqrActionPerformed

    private void BtnRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRootActionPerformed
    Display = TxtAreaOutput.getText() + BtnRoot.getText() + "(";
    equasion = equasion + "Math.sqrt(";
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnRootActionPerformed

    private void BtnFractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFractionActionPerformed
        Fraction Fraction = new Fraction(new javax.swing.JFrame(), true);
        Fraction.setVisible(true);
        if(!Fraction.cancel())
        {
            String numerator = Fraction.getjTextField1();
            String denominator = Fraction.getjTextField2();
            if(!numerator.equals("") && !denominator.equals(""))
                {
            equasion = equasion + "(" + numerator + "/" + denominator + ")";
            numerator = Super(numerator);
            denominator = Sub(denominator);
            Display = Display + "(" + numerator + "/" + denominator + ")";
            TxtAreaDebug.setText(equasion);
            TxtAreaOutput.setText(Display);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Both Boxes must be fiilled");
        }
    }
    }//GEN-LAST:event_BtnFractionActionPerformed

    private void BtnCubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCubeRootActionPerformed
    String cubeRootStr = JOptionPane.showInputDialog(rootPane, "Cubed Root of: ");
    int cubeRootInt = Integer.parseInt(cubeRootStr);
    Display = TxtAreaOutput.getText() + Super("3") + BtnRoot.getText() + "(" + cubeRootStr + ")";
    equasion = equasion + Math.cbrt(cubeRootInt);
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }//GEN-LAST:event_BtnCubeRootActionPerformed

    private void BtnCustRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustRootActionPerformed
    Cust_Root Root = new Cust_Root(new javax.swing.JFrame(), true);
    Root.setVisible(true);
    if(!Root.cancel())
    {
    equasion = equasion + "Math.round(Math.pow(" + Root.getjTextField2() + ", 1.0 / " + Root.getjTextField1() + "))";
    Display = Display + Super(Root.getjTextField1()) + BtnRoot.getText() +"("+ Root.getjTextField2() + ")";
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);
    }
    }//GEN-LAST:event_BtnCustRootActionPerformed

    private void BtnMixedFractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMixedFractionActionPerformed
        Mixed_Fraction MixedF = new Mixed_Fraction(new javax.swing.JFrame(), true);
        MixedF.setVisible(true);
        //try
        //{
            String numerator = MixedF.getjTextField1();
            String denominator = MixedF.getjTextField2();
            String whole = MixedF.getjTextField3();
            equasion = equasion + "(" + whole + "*" + "(" + numerator + "/" + denominator + "))";
            numerator = Super(numerator);
            denominator = Sub(denominator);
            Display = Display + "(" + whole + "x" + "(" + numerator + "/" + denominator + "))";
            TxtAreaDebug.setText(equasion);
            TxtAreaOutput.setText(Display);
        //}
        //catch(NullPointerException e)
        //{
        //    JOptionPane.showMessageDialog(rootPane, "Both Boxes must be fiilled");
        //    ETCBA++;
        //}
    }//GEN-LAST:event_BtnMixedFractionActionPerformed

    private void BtnAbsoluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbsoluteActionPerformed
        
        if(abs == 0)
        {
        Display = TxtAreaOutput.getText() + "|";
        equasion = equasion + "Math.abs(";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
        abs++;
        }
        else if(abs == 1)
        {
        Display = TxtAreaOutput.getText() + "|";
        equasion = equasion + ")";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
        abs--;
        }
    }//GEN-LAST:event_BtnAbsoluteActionPerformed

    private void Btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn11ActionPerformed
    Settings Settings = new Settings(new javax.swing.JFrame(), true);
    Settings.setVisible(true);
    type = Settings.getUnitType();
    Output = Settings.getOutputType();
    place = Settings.getPlace();
    }//GEN-LAST:event_Btn11ActionPerformed

    private void BtnCustRoot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustRoot2ActionPerformed
    Display = TxtAreaOutput.getText() + "sin"+ Super("-1") +"(";
    equasion = equasion + "Math.asin(";
    TxtAreaDebug.setText(equasion);
    TxtAreaOutput.setText(Display);

    }//GEN-LAST:event_BtnCustRoot2ActionPerformed

    private void BtnSin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSin1ActionPerformed
    shift = true;
    }//GEN-LAST:event_BtnSin1ActionPerformed

    private void BtnDot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDot1ActionPerformed
        if(!shift)
        {
        Display = TxtAreaOutput.getText() + "x₁₀(";
        equasion = equasion + "*Math.pow(10,";
        TxtAreaDebug.setText(equasion);
        TxtAreaOutput.setText(Display);
        }
        else
        {
            Display = TxtAreaOutput.getText() + jLabel2.getText();
            equasion = equasion + "Math.PI";
            TxtAreaDebug.setText(equasion);
            TxtAreaOutput.setText(Display);
        }
    }//GEN-LAST:event_BtnDot1ActionPerformed

    private void BtnAbsolute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbsolute1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAbsolute1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnAbsolute;
    private javax.swing.JButton BtnAbsolute1;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnCos;
    private javax.swing.JButton BtnCubeRoot;
    private javax.swing.JButton BtnCustRoot;
    private javax.swing.JButton BtnCustRoot2;
    private javax.swing.JButton BtnDevide;
    private javax.swing.JButton BtnDot;
    private javax.swing.JButton BtnDot1;
    private javax.swing.JButton BtnEquals;
    private javax.swing.JButton BtnFraction;
    private javax.swing.JButton BtnMinus;
    private javax.swing.JButton BtnMixedFraction;
    private javax.swing.JButton BtnMultiply;
    private javax.swing.JButton BtnOpen;
    private javax.swing.JButton BtnPlus;
    private javax.swing.JButton BtnRoot;
    private javax.swing.JButton BtnSin;
    private javax.swing.JButton BtnSin1;
    private javax.swing.JButton BtnSqr;
    private javax.swing.JButton BtnTan;
    private javax.swing.JTextField TxtAreaDebug;
    private javax.swing.JTextField TxtAreaOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
